### ISSUE TITLE
Mismatch between Scaleway Dedibox and Scaleway Elements APIs

### ISSUE THREAD

**Issue by Amaury** [vanonox/certbot-dns-scaleway#1]
Hi,

It looks like the certbot-dns-scaleway plugin uses the _Scaleway Elements API_, and not the _Scaleway Dedibox API_.
It's a bit disturbing and misleading, but the two offers are different:

- Scaleway Dedibox provides dedicated servers and domain name registration (with free DNS server for the registered domains).
- Scaleway Elements provides cloud services including DNS server (but not domain registration).

So, in order to use the certbot-dns-scaleway plugin with Scaleway, we have to:

- Create an account on Scaleway Dedibox
- Buy a domain name on Scaleway Dedibox
- Create an account on Scaleway Elements
- Use the DNS service to manage the "external" domain
- Create an API key on Scaleway Elements

As it is now, the plugin is almost useless. It would be a lot easier if the plugin was able to use the Scaleway Dedibox API, to directly manage the domain without having to use a separate DNS service.

Is it something you can think about?

Best regards,

Amaury

**Comment by vanonox** [comment]
Hi,
i understand your confusion.
it seems you have got an answer on the community slack of Scaleway
you may be able to use https://pypi.org/project/certbot-dns-online/ ?

regards

**Comment by Amaury** [comment]
Thank you, I missed this one!
